/*
 * Copyright (c) 2012-2017 The ANTLR Project. All rights reserved.
 * Use of this file is governed by the BSD 3-clause license that
 * can be found in the LICENSE.txt file in the project root.
 */

/*
 eslint-disable @typescript-eslint/no-namespace, @typescript-eslint/naming-convention, no-redeclare,
 max-classes-per-file, jsdoc/check-tag-names, @typescript-eslint/no-empty-function,
 @typescript-eslint/restrict-plus-operands, @typescript-eslint/unified-signatures, @typescript-eslint/member-ordering,
 no-underscore-dangle, max-len
*/

/* cspell: disable */




import { java } from "../../../../../lib/java/java";
import { Token } from "./Token";
import { Vocabulary } from "./Vocabulary";


import { JavaObject } from "../../../../../lib/java/lang/Object";


/**
 * This class provides a default implementation of the {@link Vocabulary}
 * interface.
 *
 * @author Sam Harwell
 */
export  class VocabularyImpl extends JavaObject implements Vocabulary {
	private static readonly  EMPTY_NAMES:  java.lang.String[] | null = new   Array<java.lang.String>(0);

	/**
	 * Gets an empty {@link Vocabulary} instance.
	 *
	 * <p>
	 * No literal or symbol names are assigned to token types, so
	 * {@link #getDisplayName(int)} returns the numeric value for all tokens
	 * except {@link Token#EOF}.</p>
	 */
	public static readonly  EMPTY_VOCABULARY:  VocabularyImpl | null = new  VocabularyImpl(VocabularyImpl.EMPTY_NAMES, VocabularyImpl.EMPTY_NAMES, VocabularyImpl.EMPTY_NAMES);


	private readonly  literalNames:  java.lang.String[] | null;

	private readonly  symbolicNames:  java.lang.String[] | null;

	private readonly  displayNames:  java.lang.String[] | null;

	private readonly  maxTokenType:  number;

	/**
	 * Constructs a new instance of {@link VocabularyImpl} from the specified
	 * literal and symbolic token names.
	 *
	 * @param literalNames The literal names assigned to tokens, or {@code null}
	 * if no literal names are assigned.
	 * @param symbolicNames The symbolic names assigned to tokens, or
	 * {@code null} if no symbolic names are assigned.
	 *
	 * @see #getLiteralName(int)
	 * @see #getSymbolicName(int)
	 */
	/* eslint-disable constructor-super, @typescript-eslint/no-unsafe-call */
public constructor(literalNames: java.lang.String[]| null, symbolicNames: java.lang.String[]| null);

	/**
	 * Constructs a new instance of {@link VocabularyImpl} from the specified
	 * literal, symbolic, and display token names.
	 *
	 * @param literalNames The literal names assigned to tokens, or {@code null}
	 * if no literal names are assigned.
	 * @param symbolicNames The symbolic names assigned to tokens, or
	 * {@code null} if no symbolic names are assigned.
	 * @param displayNames The display names assigned to tokens, or {@code null}
	 * to use the values in {@code literalNames} and {@code symbolicNames} as
	 * the source of display names, as described in
	 * {@link #getDisplayName(int)}.
	 *
	 * @see #getLiteralName(int)
	 * @see #getSymbolicName(int)
	 * @see #getDisplayName(int)
	 */
	public constructor(literalNames: java.lang.String[]| null, symbolicNames: java.lang.String[]| null, displayNames: java.lang.String[]| null);
/* @ts-expect-error, because of the super() call in the closure. */
public constructor(literalNames: java.lang.String[] | null, symbolicNames: java.lang.String[] | null, displayNames?: java.lang.String[] | null) {
const $this = (literalNames: java.lang.String[] | null, symbolicNames: java.lang.String[] | null, displayNames?: java.lang.String[] | null): void => {
if (displayNames === undefined) {
		$this(literalNames, symbolicNames, null);
	}
 else  {

/* @ts-expect-error, because of the super() call in the closure. */
		super();
this.literalNames = literalNames !== null ? literalNames : VocabularyImpl.EMPTY_NAMES;
		this.symbolicNames = symbolicNames !== null ? symbolicNames : VocabularyImpl.EMPTY_NAMES;
		this.displayNames = displayNames !== null ? displayNames : VocabularyImpl.EMPTY_NAMES;
		// See note here on -1 part: https://github.com/antlr/antlr4/pull/1146
		this.maxTokenType =
			Math.max(this.displayNames.length,
					 Math.max(this.literalNames.length, this.symbolicNames.length)) - 1;
	}
};

$this(literalNames, symbolicNames, displayNames);

}
/* eslint-enable constructor-super, @typescript-eslint/no-unsafe-call */

	/**
	 * Returns a {@link VocabularyImpl} instance from the specified set of token
	 * names. This method acts as a compatibility layer for the single
	 * {@code tokenNames} array generated by previous releases of ANTLR.
	 *
	 * <p>The resulting vocabulary instance returns {@code null} for
	 * {@link #getLiteralName(int)} and {@link #getSymbolicName(int)}, and the
	 * value from {@code tokenNames} for the display names.</p>
	 *
	 * @param tokenNames The token names, or {@code null} if no token names are
	 * available.
	  @returns A {@link Vocabulary} instance which uses {@code tokenNames} for
	 * the display names of tokens.
	 */
	public static fromTokenNames = (tokenNames: java.lang.String[]| null):  Vocabulary | null => {
		if (tokenNames === null || tokenNames.length === 0) {
			return VocabularyImpl.EMPTY_VOCABULARY;
		}

		let  literalNames: java.lang.String[] = java.util.Arrays.copyOf(tokenNames, tokenNames.length);
		let  symbolicNames: java.lang.String[] = java.util.Arrays.copyOf(tokenNames, tokenNames.length);
		for (let  i: number = 0; i < tokenNames.length; i++) {
			let  tokenName: java.lang.String = tokenNames[i];
			if (tokenName === null) {
				continue;
			}

			if (!tokenName.isEmpty()) {
				let  firstChar: CodePoint = tokenName.charAt(0);
				if (firstChar === '\'') {
					symbolicNames[i] = null;
					continue;
				}
				else { if (java.lang.Character.isUpperCase(firstChar)) {
					literalNames[i] = null;
					continue;
				}
}

			}

			// wasn't a literal or symbolic name
			literalNames[i] = null;
			symbolicNames[i] = null;
		}

		return new  VocabularyImpl(literalNames, symbolicNames, tokenNames);
	}

	public getMaxTokenType = ():  number => {
		return this.maxTokenType;
	}

	public getLiteralName = (tokenType: number):  java.lang.String | null => {
		if (tokenType >= 0 && tokenType < this.literalNames.length) {
			return this.literalNames[tokenType];
		}

		return null;
	}

	public getSymbolicName = (tokenType: number):  java.lang.String | null => {
		if (tokenType >= 0 && tokenType < this.symbolicNames.length) {
			return this.symbolicNames[tokenType];
		}

		if (tokenType === Token.EOF) {
			return "EOF";
		}

		return null;
	}

	public getDisplayName = (tokenType: number):  java.lang.String | null => {
		if (tokenType >= 0 && tokenType < this.displayNames.length) {
			let  displayName: java.lang.String = this.displayNames[tokenType];
			if (displayName !== null) {
				return displayName;
			}
		}

		let  literalName: java.lang.String = this.getLiteralName(tokenType);
		if (literalName !== null) {
			return literalName;
		}

		let  symbolicName: java.lang.String = this.getSymbolicName(tokenType);
		if (symbolicName !== null) {
			return symbolicName;
		}

		return java.lang.Integer.toString(tokenType);
	}

	// Because this is an actual implementation object, we can provide access methods for vocabulary symbols

	public getLiteralNames = ():  java.lang.String[] | null => {
		return this.literalNames;
	}

	public getSymbolicNames = ():  java.lang.String[] | null => {
		return this.symbolicNames;
	}

	public getDisplayNames = ():  java.lang.String[] | null => {
		return this.displayNames;
	}
}
